"""Project package for the federated PEFT empirical pipeline."""

from .config import ExperimentConfig, LocalPaths, ModelConfig
from .data_pipeline import (
    ClientAssignment,
    ClientExample,
    StandardizedExample,
    TokenizationConfig,
    build_client_dataloaders,
    group_examples_by_client,
    load_client_assignments,
    load_from_sqlite,
    load_standardized_examples,
    merge_examples_with_assignments,
    render_client_data_summary,
)
from .evaluation import EvaluationResult, evaluate_client_loaders, evaluate_dataloader, render_evaluation_result
from .federated import (
    ClientRoundResult,
    FederatedRunConfig,
    FederatedRunResult,
    RoundLog,
    append_round_log,
    build_experiment_grid,
    render_run_summary,
    run_experiment_grid,
    run_federated_simulation,
    sample_clients_for_round,
    write_metrics_file,
)
from .local_train import LocalTrainConfig, LocalTrainResult, render_local_train_result, train_local_client
from .modeling import (
    ModelBundle,
    attach_peft_adapter,
    build_model_bundle,
    count_parameters,
    create_model_load_kwargs,
    create_tokenizer_load_kwargs,
    load_base_causal_lm,
    load_tokenizer,
    render_model_bundle_summary,
)
from .peft_state import (
    add_trainable_states,
    average_trainable_states,
    clone_trainable_state,
    extract_trainable_state,
    load_trainable_state,
    render_trainable_state_summary,
    scale_trainable_state,
    subtract_trainable_states,
    trainable_state_l2_norm,
    zero_like_trainable_state,
)

__all__ = [
    "ClientAssignment",
    "ClientExample",
    "ClientRoundResult",
    "EvaluationResult",
    "ExperimentConfig",
    "FederatedRunConfig",
    "FederatedRunResult",
    "LocalPaths",
    "LocalTrainConfig",
    "LocalTrainResult",
    "ModelBundle",
    "ModelConfig",
    "RoundLog",
    "StandardizedExample",
    "TokenizationConfig",
    "add_trainable_states",
    "attach_peft_adapter",
    "average_trainable_states",
    "append_round_log",
    "build_client_dataloaders",
    "build_model_bundle",
    "build_experiment_grid",
    "clone_trainable_state",
    "count_parameters",
    "create_model_load_kwargs",
    "create_tokenizer_load_kwargs",
    "evaluate_client_loaders",
    "evaluate_dataloader",
    "extract_trainable_state",
    "group_examples_by_client",
    "load_base_causal_lm",
    "load_client_assignments",
    "load_from_sqlite",
    "load_standardized_examples",
    "load_tokenizer",
    "load_trainable_state",
    "merge_examples_with_assignments",
    "render_client_data_summary",
    "render_evaluation_result",
    "render_local_train_result",
    "render_model_bundle_summary",
    "render_run_summary",
    "render_trainable_state_summary",
    "run_experiment_grid",
    "run_federated_simulation",
    "sample_clients_for_round",
    "write_metrics_file",
    "scale_trainable_state",
    "subtract_trainable_states",
    "trainable_state_l2_norm",
    "train_local_client",
    "zero_like_trainable_state",
]
